name: "Build & Deploy Page"
on:
  push:
    branches:
      - master
  schedule:
   # Run every morning to ensure component documentation is up to date on deployment
   - cron: '23 5 * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout ros2_control
      uses: actions/checkout@v2
      with:
        repository: ros-controls/ros2_control@master
        path: ros2_control
    - uses: ros-controls/control.ros.org-deployment-scripts@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
        install_extensions: false
        deploy: true
