on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - uses: seanzhengw/sphinx-pages@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
